[platformio]
default_envs = example_motor

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
monitor_filters = send_on_enter

[env:example_motor]
build_src_filter =
    +<*>
