[platformio]
default_envs = example_motor

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
    arduino-libraries/Servo @ ^1.3.0

[env:example_motor]
build_src_filter =
    +<*>
    -<main.cpp>
    -<example_servo_laser.cpp>

[env:serial_protocol]
build_src_filter =
    +<*>
    -<example_motor.cpp>
    -<example_servo_laser.cpp>

[env:example_servo_laser]
build_src_filter =
    +<*>
    -<example_motor.cpp>
    -<main.cpp>
